### ISSUE TITLE
`JSONType` breaks SQLAlchemy

### ISSUE THREAD

**Issue by gera2ld** [python-social-auth/social-storage-sqlalchemy#1]
According to SQLAlchemy, the `PickleType`  has a `pickler` **with pickle-compatible `dumps` and `loads` methods**, which means the `dumps` method may have more than one positional argument.

But `JSONType` in this library breaks this since `pickler = json` and `json.dumps` has only one positional argument.

The error log is like this:
```
Traceback (most recent call last):
  File ".../python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1116, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File ".../python/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 622, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File ".../python/lib/python3.6/site-packages/sqlalchemy/sql/sqltypes.py", line 1467, in process
    value = dumps(value, protocol)
TypeError: dumps() takes 1 positional argument but 2 were given
```

**Comment by omab** [comment]
Fixed by https://github.com/python-social-auth/social-storage-sqlalchemy/commit/39d129c1718dfab6be33bec69b1c44853e66da86
